name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Lint and Format Code
        run: |
          npm run lint
          npm run format

      - name: Check Dependency Security
        run: |
          npm audit --audit-level=high
          # or use Snyk or other security scanning tool

      - name: Run Tests
        run: npm test -- --coverage

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: coverage
